//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignVerify.Providers.XadesProvider.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignVerify.Providers.XadesProvider.Lang.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תעודות חסרות..
        /// </summary>
        public static string CertificateChainError {
            get {
                return ResourceManager.GetString("CertificateChainError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חתימה נוספת בתקן Xades אינה נתמכת בגרסה זו..
        /// </summary>
        public static string CosignNotSupported {
            get {
                return ResourceManager.GetString("CosignNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המידע לא מצוי על הקובץ..
        /// </summary>
        public static string EmptyData {
            get {
                return ResourceManager.GetString("EmptyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to במצב detached מסלול הקובץ הינו חובה..
        /// </summary>
        public static string FileNameMissing {
            get {
                return ResourceManager.GetString("FileNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חתימה במקביל נכשלה מאחר ולא קיימת תעודה על הקובץ החתום..
        /// </summary>
        public static string NoCerteficateFound {
            get {
                return ResourceManager.GetString("NoCerteficateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן להשתמש בתעודה זו לחתימה מאחר שהיא אינה מכילה מפתח פרטי..
        /// </summary>
        public static string NotContainingPrivateKey {
            get {
                return ResourceManager.GetString("NotContainingPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תהליך אכסון נכשל מאחר ולא קיים תעודה על הקובץ החתום..
        /// </summary>
        public static string NotContainingSignatureInfo {
            get {
                return ResourceManager.GetString("NotContainingSignatureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הקובץ חתום בתקו Xades הוא אינו יכול להיחתם שוב באמצעות תקן שונה..
        /// </summary>
        public static string OtherProvider {
            get {
                return ResourceManager.GetString("OtherProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן לחתום על הקובץ מכוון שפרמטרים חסרים..
        /// </summary>
        public static string ParametersMissing {
            get {
                return ResourceManager.GetString("ParametersMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פעולת החתימה הופסקה על ידי המשתמש.
        /// </summary>
        public static string SignCanceled {
            get {
                return ResourceManager.GetString("SignCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to החתימה נכשלה, הסתכל בקובץ השגיאות לקבלת פרטים נוספים. .
        /// </summary>
        public static string SignFailed {
            get {
                return ResourceManager.GetString("SignFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אמות נכשל מאחר ולא קיימת תעודה על הקובץ החתום..
        /// </summary>
        public static string VeiifyNoCerteficate {
            get {
                return ResourceManager.GetString("VeiifyNoCerteficate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האימות נכשל, הסתכל בקובץ השגיאות לקבלת פרטים נוספים. .
        /// </summary>
        public static string VerifyFailed {
            get {
                return ResourceManager.GetString("VerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הקובץ אינו קובץ חתום תקין..
        /// </summary>
        public static string WrongFile {
            get {
                return ResourceManager.GetString("WrongFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הסיסמא שהוקשה שגויה, נסה שנית..
        /// </summary>
        public static string WrongPinCode {
            get {
                return ResourceManager.GetString("WrongPinCode", resourceCulture);
            }
        }
    }
}
