'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ControlStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SignVerify.GUI.ControlStrings", GetType(ControlStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בטל.
        '''</summary>
        Friend Shared ReadOnly Property AlreadySignMessageDiagCancel_Button() As String
            Get
                Return ResourceManager.GetString("AlreadySignMessageDiagCancel_Button", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to החתימה קיימת כבר.
        '''</summary>
        Friend Shared ReadOnly Property AlreadySignMessageDiagForm() As String
            Get
                Return ResourceManager.GetString("AlreadySignMessageDiagForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הקובץ כבר מכיל את התעודה. האם אתה רוצה לחתום את הקובץ שוב עם אותה התעודה?.
        '''</summary>
        Friend Shared ReadOnly Property AlreadySignMessageDiaglblMessage() As String
            Get
                Return ResourceManager.GetString("AlreadySignMessageDiaglblMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חתום.
        '''</summary>
        Friend Shared ReadOnly Property AlreadySignMessageDiagOK_Button() As String
            Get
                Return ResourceManager.GetString("AlreadySignMessageDiagOK_Button", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הגדרות.
        '''</summary>
        Friend Shared ReadOnly Property btnAdvancedSettings_Button() As String
            Get
                Return ResourceManager.GetString("btnAdvancedSettings_Button", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to עצירת פעולה.....
        '''</summary>
        Friend Shared ReadOnly Property Cancelation() As String
            Get
                Return ResourceManager.GetString("Cancelation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ביטול תהליך חתימה במקביל....  .
        '''</summary>
        Friend Shared ReadOnly Property CancelCosign() As String
            Get
                Return ResourceManager.GetString("CancelCosign", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to עצירת חתימה.....
        '''</summary>
        Friend Shared ReadOnly Property CancelSign() As String
            Get
                Return ResourceManager.GetString("CancelSign", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to עצירת אימות במקביל.....
        '''</summary>
        Friend Shared ReadOnly Property CancelVerify() As String
            Get
                Return ResourceManager.GetString("CancelVerify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אל תציג מסך זה יותר.
        '''</summary>
        Friend Shared ReadOnly Property DontShowSignOption() As String
            Get
                Return ResourceManager.GetString("DontShowSignOption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הודעת שגיאה.
        '''</summary>
        Friend Shared ReadOnly Property errorDiagForm() As String
            Get
                Return ResourceManager.GetString("errorDiagForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אשר.
        '''</summary>
        Friend Shared ReadOnly Property errorDiagOK_Button() As String
            Get
                Return ResourceManager.GetString("errorDiagOK_Button", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ליצור עותק נוסף.
        '''</summary>
        Friend Shared ReadOnly Property fileExistCopyBtn() As String
            Get
                Return ResourceManager.GetString("fileExistCopyBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לדרוס.
        '''</summary>
        Friend Shared ReadOnly Property fileExistReplaceBtn() As String
            Get
                Return ResourceManager.GetString("fileExistReplaceBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to עבור לבחירה מתקדמת.
        '''</summary>
        Friend Shared ReadOnly Property FileSelectionBtnAdvancedSearch() As String
            Get
                Return ResourceManager.GetString("FileSelectionBtnAdvancedSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to עבור לבחירה רגילה.
        '''</summary>
        Friend Shared ReadOnly Property FileSelectionBtnRegularSearch() As String
            Get
                Return ResourceManager.GetString("FileSelectionBtnRegularSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הקבצים שנבחרו.
        '''</summary>
        Friend Shared ReadOnly Property FileSelectionTitleAdvancedSearch() As String
            Get
                Return ResourceManager.GetString("FileSelectionTitleAdvancedSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בטל.
        '''</summary>
        Friend Shared ReadOnly Property frmProgressBarbtnCancel() As String
            Get
                Return ResourceManager.GetString("frmProgressBarbtnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to התקדמות.
        '''</summary>
        Friend Shared ReadOnly Property frmProgressBarbtnForm() As String
            Get
                Return ResourceManager.GetString("frmProgressBarbtnForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to תהליך של חתימה על חתימה בביצוע.
        '''</summary>
        Friend Shared ReadOnly Property frmProgressBarCosignAction() As String
            Get
                Return ResourceManager.GetString("frmProgressBarCosignAction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to תהליך של חתימה בביצוע.
        '''</summary>
        Friend Shared ReadOnly Property frmProgressBarSignAction() As String
            Get
                Return ResourceManager.GetString("frmProgressBarSignAction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to תהליך של אישור חתימה בביצוע .
        '''</summary>
        Friend Shared ReadOnly Property frmProgressBarVerifyAction() As String
            Get
                Return ResourceManager.GetString("frmProgressBarVerifyAction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to המערכת לא מכילה את פרטי הכרטיס..
        '''</summary>
        Friend Shared ReadOnly Property lNoCardDetailsblMessage() As String
            Get
                Return ResourceManager.GetString("lNoCardDetailsblMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מיקום הקובץ החתום:.
        '''</summary>
        Friend Shared ReadOnly Property lVerifyDialoglblSignedFileLocation() As String
            Get
                Return ResourceManager.GetString("lVerifyDialoglblSignedFileLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פרופיל זה מאפשר חתימה על קבצי PDF בלבד. בחירת הפרופיל תבטל את בחירת הקבצים הנוכחית. האם להמשיך?.
        '''</summary>
        Friend Shared ReadOnly Property MoveToPdfQuestion() As String
            Get
                Return ResourceManager.GetString("MoveToPdfQuestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to שינוי פרופיל.
        '''</summary>
        Friend Shared ReadOnly Property MoveToPdfTitle() As String
            Get
                Return ResourceManager.GetString("MoveToPdfTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא.
        '''</summary>
        Friend Shared ReadOnly Property No() As String
            Get
                Return ResourceManager.GetString("No", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פרטי תעודה חסרים.
        '''</summary>
        Friend Shared ReadOnly Property NoCardDetailsForm() As String
            Get
                Return ResourceManager.GetString("NoCardDetailsForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to התעודה הינה תעודה לא מאושרת או שהכרטיס או התעודה חסרים..
        '''</summary>
        Friend Shared ReadOnly Property NoCardDetailsMessage() As String
            Get
                Return ResourceManager.GetString("NoCardDetailsMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אשר.
        '''</summary>
        Friend Shared ReadOnly Property NoCardDetailsOK_Button() As String
            Get
                Return ResourceManager.GetString("NoCardDetailsOK_Button", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לחץ לפרוט.
        '''</summary>
        Friend Shared ReadOnly Property NotCoverWholeDocument() As String
            Get
                Return ResourceManager.GetString("NotCoverWholeDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to החתימה לא מכסה את כל המסמך.
        '''</summary>
        Friend Shared ReadOnly Property NotCoverWholeDocumentExplaination() As String
            Get
                Return ResourceManager.GetString("NotCoverWholeDocumentExplaination", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to עיון.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiagbtnBrowseDestinationFile() As String
            Get
                Return ResourceManager.GetString("OptionDiagbtnBrowseDestinationFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בטל.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiagCancel_Button() As String
            Get
                Return ResourceManager.GetString("OptionDiagCancel_Button", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הוסף חתימה על זמן.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiagcbCheckTimeStamp() As String
            Get
                Return ResourceManager.GetString("OptionDiagcbCheckTimeStamp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בדוק רשימות פסולות.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiagcbCRL() As String
            Get
                Return ResourceManager.GetString("OptionDiagcbCRL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בדוק שהזמן שבו בוצעה החתימה נמצא בחתימה.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiagcbDisplayTimeStamp() As String
            Get
                Return ResourceManager.GetString("OptionDiagcbDisplayTimeStamp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בדוק מסלול התעודה.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiagcbPath() As String
            Get
                Return ResourceManager.GetString("OptionDiagcbPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הצג רק תעודות מאושרות.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiagcbShowOnlyNonRepudiation() As String
            Get
                Return ResourceManager.GetString("OptionDiagcbShowOnlyNonRepudiation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הגדרות משתמש.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiagForm() As String
            Get
                Return ResourceManager.GetString("OptionDiagForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הגדרות מתקדמות לחתימה:.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiaglblAdvancedSeetingsSign() As String
            Get
                Return ResourceManager.GetString("OptionDiaglblAdvancedSeetingsSign", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הגדרות מתקדמות לאימות:.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiaglblAdvancedSeetingsVerify() As String
            Get
                Return ResourceManager.GetString("OptionDiaglblAdvancedSeetingsVerify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הגדרות להכנת קבצים חתומים:.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiaglblChooseHeader() As String
            Get
                Return ResourceManager.GetString("OptionDiaglblChooseHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בדיקה האם התעודות אינן פסולות.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiaglblCRLExplain() As String
            Get
                Return ResourceManager.GetString("OptionDiaglblCRLExplain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to תקן:.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiaglblFormat() As String
            Get
                Return ResourceManager.GetString("OptionDiaglblFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בחר את הגדרות המשתמש לחתימה ולאימות.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiaglblHeader() As String
            Get
                Return ResourceManager.GetString("OptionDiaglblHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בדיקת רמות האישור של ספקי התעודה (הרשות המאשרת ואישור הביניים).
        '''</summary>
        Friend Shared ReadOnly Property OptionDiaglblPathExplain() As String
            Get
                Return ResourceManager.GetString("OptionDiaglblPathExplain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פרופיל:.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiaglblProfile() As String
            Get
                Return ResourceManager.GetString("OptionDiaglblProfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בחר פרופיל הגדרות לחתימה:.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiaglblSelectProfile() As String
            Get
                Return ResourceManager.GetString("OptionDiaglblSelectProfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אלגוריתם חתימה.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiaglblSigingAlgorithm() As String
            Get
                Return ResourceManager.GetString("OptionDiaglblSigingAlgorithm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בדיקה שהחתימה כוללת זמן.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiaglblTSExplain() As String
            Get
                Return ResourceManager.GetString("OptionDiaglblTSExplain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to כתובת שרת זמן:.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiaglblTSURL() As String
            Get
                Return ResourceManager.GetString("OptionDiaglblTSURL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אשר.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiagOK_Button() As String
            Get
                Return ResourceManager.GetString("OptionDiagOK_Button", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to שמור בתיקייה אחרת.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiagRadioDifferent() As String
            Get
                Return ResourceManager.GetString("OptionDiagRadioDifferent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to שמור בתיקיית הקובץ המקורי.
        '''</summary>
        Friend Shared ReadOnly Property OptionDiagRadioSame() As String
            Get
                Return ResourceManager.GetString("OptionDiagRadioSame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הוסף הצגה ויזואלית של חותמת בנוסף לסימון החתימה ב Adobe Reader.
        '''</summary>
        Friend Shared ReadOnly Property PdfOptionDiagcbShowImage() As String
            Get
                Return ResourceManager.GetString("PdfOptionDiagcbShowImage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הוסף הצגה ויזואלית של פרטי החותם בנוסף לסימון החתימה ב Adobe Reader.
        '''</summary>
        Friend Shared ReadOnly Property PdfOptionDiagcbShowSig() As String
            Get
                Return ResourceManager.GetString("PdfOptionDiagcbShowSig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to השתמש בתמונת ברירת מחדל של המערכת.
        '''</summary>
        Friend Shared ReadOnly Property PdfOptionDiagcbUseDefaultImage() As String
            Get
                Return ResourceManager.GetString("PdfOptionDiagcbUseDefaultImage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to תצוגת החתימה.
        '''</summary>
        Friend Shared ReadOnly Property PdfOptionDiaglblAppearanceHeader() As String
            Get
                Return ResourceManager.GetString("PdfOptionDiaglblAppearanceHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to במידה וסימנת להוסיף חתימה ויזואלית ניתן גם להגדיר מאפייני חתימה בהתאם לערכים שיוזנו בחלק של מאפייני חתימה.
        '''מאפיינים אלו מוצגים במסך מאפייני החתימה ב ADOBE  אשר זמין בלחיצה על החתימה הויזואלית ..
        '''</summary>
        Friend Shared ReadOnly Property PdfOptionDiaglblEx1() As String
            Get
                Return ResourceManager.GetString("PdfOptionDiaglblEx1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הגדרות חתימה על קבצי PDF.
        '''</summary>
        Friend Shared ReadOnly Property PdfOptionDiaglblHeader() As String
            Get
                Return ResourceManager.GetString("PdfOptionDiaglblHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הוסף תמונה :.
        '''</summary>
        Friend Shared ReadOnly Property PdfOptionDiaglblImagePath() As String
            Get
                Return ResourceManager.GetString("PdfOptionDiaglblImagePath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פרטי קשר של החותם.
        '''</summary>
        Friend Shared ReadOnly Property PdfSignOptionlblContact() As String
            Get
                Return ResourceManager.GetString("PdfSignOptionlblContact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to סימון הוספת חתימה ויזואלית מאפשר הצגת החתימה בהתאם למוגדר בחלק של תצוגת החתימה..
        '''</summary>
        Friend Shared ReadOnly Property PdfSignOptionlblDataEx() As String
            Get
                Return ResourceManager.GetString("PdfSignOptionlblDataEx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ניתן להגדיר מאפייני חתימה בהתאם לערכים שיוזנו בחלק של מאפייני חתימה..
        '''</summary>
        Friend Shared ReadOnly Property PdfSignOptionlblDataEx2() As String
            Get
                Return ResourceManager.GetString("PdfSignOptionlblDataEx2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מאפיינים אלו מוצגים במסך מאפייני החתימה ב ADOBE  אשר זמין בלחיצה על החתימה הויזואלית ..
        '''</summary>
        Friend Shared ReadOnly Property PdfSignOptionlblDataEx3() As String
            Get
                Return ResourceManager.GetString("PdfSignOptionlblDataEx3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מאפייני החתימה.
        '''</summary>
        Friend Shared ReadOnly Property PdfSignOptionlblDataHeader() As String
            Get
                Return ResourceManager.GetString("PdfSignOptionlblDataHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מקום החתימה.
        '''</summary>
        Friend Shared ReadOnly Property PdfSignOptionlblLocation() As String
            Get
                Return ResourceManager.GetString("PdfSignOptionlblLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מיקום הצגת החתימה.
        '''</summary>
        Friend Shared ReadOnly Property PdfSignOptionlblPosition() As String
            Get
                Return ResourceManager.GetString("PdfSignOptionlblPosition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to יישור.
        '''</summary>
        Friend Shared ReadOnly Property PdfSignOptionlblPositionForAlign() As String
            Get
                Return ResourceManager.GetString("PdfSignOptionlblPositionForAlign", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to כותרת.
        '''</summary>
        Friend Shared ReadOnly Property PdfSignOptionlblPositionForTitle() As String
            Get
                Return ResourceManager.GetString("PdfSignOptionlblPositionForTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הערות.
        '''</summary>
        Friend Shared ReadOnly Property PdfSignOptionlblReason() As String
            Get
                Return ResourceManager.GetString("PdfSignOptionlblReason", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הוסף פרטי החותם.
        '''</summary>
        Friend Shared ReadOnly Property PdfSignOptionlblShowName() As String
            Get
                Return ResourceManager.GetString("PdfSignOptionlblShowName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to טקסט להצגה ליד החתימה.
        '''</summary>
        Friend Shared ReadOnly Property PdfSignOptionlblText() As String
            Get
                Return ResourceManager.GetString("PdfSignOptionlblText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to התקדמות חתימה במקביל.
        '''</summary>
        Friend Shared ReadOnly Property progressCoSign() As String
            Get
                Return ResourceManager.GetString("progressCoSign", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to התקדמות חתימה.
        '''</summary>
        Friend Shared ReadOnly Property progressSign() As String
            Get
                Return ResourceManager.GetString("progressSign", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to התקדמות אימות.
        '''</summary>
        Friend Shared ReadOnly Property progressVerify() As String
            Get
                Return ResourceManager.GetString("progressVerify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בטל.
        '''</summary>
        Friend Shared ReadOnly Property RepudiationMessageDiagCancel_Button() As String
            Get
                Return ResourceManager.GetString("RepudiationMessageDiagCancel_Button", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הצגת תעודות מאושרות.
        '''</summary>
        Friend Shared ReadOnly Property RepudiationMessageDiagForm() As String
            Get
                Return ResourceManager.GetString("RepudiationMessageDiagForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ביטול הסימון יציג גם תעודות שהונפקו על ידי גורם שאינו מאושר. האם ברצונך להמשיך?.
        '''</summary>
        Friend Shared ReadOnly Property RepudiationMessageDiaglblMessage() As String
            Get
                Return ResourceManager.GetString("RepudiationMessageDiaglblMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אשר.
        '''</summary>
        Friend Shared ReadOnly Property RepudiationMessageDiagOK_Button() As String
            Get
                Return ResourceManager.GetString("RepudiationMessageDiagOK_Button", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הצג מסך אפשרויות חתימה בזמן חתימה.
        '''</summary>
        Friend Shared ReadOnly Property ShowSignOptionDialog() As String
            Get
                Return ResourceManager.GetString("ShowSignOptionDialog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to סטטוס חתימות מפורט.
        '''</summary>
        Friend Shared ReadOnly Property SignaturesHistoryFormHeader() As String
            Get
                Return ResourceManager.GetString("SignaturesHistoryFormHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to רמה .
        '''</summary>
        Friend Shared ReadOnly Property SignaturesTreeGridLevel() As String
            Get
                Return ResourceManager.GetString("SignaturesTreeGridLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חתימות.
        '''</summary>
        Friend Shared ReadOnly Property SignaturesTreeGridSinNumberPlural() As String
            Get
                Return ResourceManager.GetString("SignaturesTreeGridSinNumberPlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חתימה.
        '''</summary>
        Friend Shared ReadOnly Property SignaturesTreeGridSinNumberSingular() As String
            Get
                Return ResourceManager.GetString("SignaturesTreeGridSinNumberSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חתימה.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblad() As String
            Get
                Return ResourceManager.GetString("signatureViewlblad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to תעודה נפסלה.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlbladRevoked() As String
            Get
                Return ResourceManager.GetString("signatureViewlbladRevoked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא תקין.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlbladUnValid() As String
            Get
                Return ResourceManager.GetString("signatureViewlbladUnValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to רשימות פסולות:.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblasdfe() As String
            Get
                Return ResourceManager.GetString("signatureViewlblasdfe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to גורם מאשר:.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblChainLabel() As String
            Get
                Return ResourceManager.GetString("signatureViewlblChainLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to תקין.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblChecked() As String
            Get
                Return ResourceManager.GetString("signatureViewlblChecked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to תוקף:.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblexpirationDateLabel() As String
            Get
                Return ResourceManager.GetString("signatureViewlblexpirationDateLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חותם.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblHeader() As String
            Get
                Return ResourceManager.GetString("signatureViewlblHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חתימה תקינה, אחד או יותר מהנתונים לא נבדק.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblIsSignNoCheck() As String
            Get
                Return ResourceManager.GetString("signatureViewlblIsSignNoCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חתימה לא חוקית.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblIsSignNotValid() As String
            Get
                Return ResourceManager.GetString("signatureViewlblIsSignNotValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חתימה מאושרת.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblIsSignOk() As String
            Get
                Return ResourceManager.GetString("signatureViewlblIsSignOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מנפיק.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblIssuerLabel() As String
            Get
                Return ResourceManager.GetString("signatureViewlblIssuerLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא נבדק.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlbllUnChecked() As String
            Get
                Return ResourceManager.GetString("signatureViewlbllUnChecked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to שם:.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblNameLabel() As String
            Get
                Return ResourceManager.GetString("signatureViewlblNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to תקן חתימה.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblStandard() As String
            Get
                Return ResourceManager.GetString("signatureViewlblStandard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to סטאטוס תעודת הזמן.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblTSCertLabel() As String
            Get
                Return ResourceManager.GetString("signatureViewlblTSCertLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to זמן חתימה:.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblTSLabel() As String
            Get
                Return ResourceManager.GetString("signatureViewlblTSLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to תעודה.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblTsNameLabel() As String
            Get
                Return ResourceManager.GetString("signatureViewlblTsNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to סטטוס זמן חתימה:.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblTSStateLabel() As String
            Get
                Return ResourceManager.GetString("signatureViewlblTSStateLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to עיון.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionbtnBrowseDestinationFile() As String
            Get
                Return ResourceManager.GetString("SignOptionbtnBrowseDestinationFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to סטטוס חתימות.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionbtnbtnSignsHistory() As String
            Get
                Return ResourceManager.GetString("SignOptionbtnbtnSignsHistory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בחר תעודה.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionbtnOpenCertDiag() As String
            Get
                Return ResourceManager.GetString("SignOptionbtnOpenCertDiag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פתח קובץ מקורי.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionbtnOpenOriginalFile() As String
            Get
                Return ResourceManager.GetString("SignOptionbtnOpenOriginalFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בטל.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionCancel_Buttone() As String
            Get
                Return ResourceManager.GetString("SignOptionCancel_Buttone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אפשרויות חתימה.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionForm() As String
            Get
                Return ResourceManager.GetString("SignOptionForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בחר תעודה לביצוע החתימה:.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionlblChooseCert() As String
            Get
                Return ResourceManager.GetString("SignOptionlblChooseCert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בחר הגדרות לחתימה נוספת:.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionlblChooseCosign() As String
            Get
                Return ResourceManager.GetString("SignOptionlblChooseCosign", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הגדרות להכנת קבצים חתומים.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionlblChooseHeader() As String
            Get
                Return ResourceManager.GetString("SignOptionlblChooseHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בחר כיצד ברצונך לחתום על הקובץ.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionlblHeader() As String
            Get
                Return ResourceManager.GetString("SignOptionlblHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to נמצאו מספר תעודות מתאימות לחתימה. אנא בחר תעודה לחתימה.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionlblManyCertificates() As String
            Get
                Return ResourceManager.GetString("SignOptionlblManyCertificates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא נמצאו תעודות לחתימה, בבקשה הוסף תעודה לחתימה..
        '''</summary>
        Friend Shared ReadOnly Property SignOptionlblNoCertificate() As String
            Get
                Return ResourceManager.GetString("SignOptionlblNoCertificate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חתימה במקביל לחתימה היא חתימה נוספת באותה רמה.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionlblParallel() As String
            Get
                Return ResourceManager.GetString("SignOptionlblParallel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אופן הכנת קבצים:.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionlblSavingType() As String
            Get
                Return ResourceManager.GetString("SignOptionlblSavingType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בחר פרופיל הגדרות לחתימה:.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionlblSelectProfile() As String
            Get
                Return ResourceManager.GetString("SignOptionlblSelectProfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חתימה מעל לחתימה היא חתימה נוספת ברמה נוספת.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionlblSerial() As String
            Get
                Return ResourceManager.GetString("SignOptionlblSerial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חתום.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionOK_Button() As String
            Get
                Return ResourceManager.GetString("SignOptionOK_Button", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to תעודה לביצוע החתימה:.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionOneCertificate() As String
            Get
                Return ResourceManager.GetString("SignOptionOneCertificate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to שמור בתיקייה אחרת.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionRadioDifferent() As String
            Get
                Return ResourceManager.GetString("SignOptionRadioDifferent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חתימה במקביל  לחתימה.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionradioParallel() As String
            Get
                Return ResourceManager.GetString("SignOptionradioParallel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to שמור בתיקיית הקובץ המקורי.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionRadioSame() As String
            Get
                Return ResourceManager.GetString("SignOptionRadioSame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חתימה על חתימה.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionradioSerial() As String
            Get
                Return ResourceManager.GetString("SignOptionradioSerial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הוסף.
        '''</summary>
        Friend Shared ReadOnly Property SignVerifybtnBrowse() As String
            Get
                Return ResourceManager.GetString("SignVerifybtnBrowse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to English.
        '''</summary>
        Friend Shared ReadOnly Property SignVerifybtnChangeLanguage() As String
            Get
                Return ResourceManager.GetString("SignVerifybtnChangeLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to עזרה.
        '''</summary>
        Friend Shared ReadOnly Property SignVerifybtnHelp() As String
            Get
                Return ResourceManager.GetString("SignVerifybtnHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הצג פרטי כרטיס.
        '''</summary>
        Friend Shared ReadOnly Property SignVerifybtnShowCardDetails() As String
            Get
                Return ResourceManager.GetString("SignVerifybtnShowCardDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חתום.
        '''</summary>
        Friend Shared ReadOnly Property SignVerifybtnSign() As String
            Get
                Return ResourceManager.GetString("SignVerifybtnSign", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הגדרות מערכת.
        '''</summary>
        Friend Shared ReadOnly Property SignVerifybtnSystemSettings() As String
            Get
                Return ResourceManager.GetString("SignVerifybtnSystemSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אמת.
        '''</summary>
        Friend Shared ReadOnly Property SignVerifybtnVerify() As String
            Get
                Return ResourceManager.GetString("SignVerifybtnVerify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לחץ לפרטים.
        '''</summary>
        Friend Shared ReadOnly Property SignVerifyClickForDetails() As String
            Get
                Return ResourceManager.GetString("SignVerifyClickForDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to קובץ ZIP המכיל את הקבצים החתומים.
        '''</summary>
        Friend Shared ReadOnly Property SignVerifyFileResultZipped() As String
            Get
                Return ResourceManager.GetString("SignVerifyFileResultZipped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הקובץ כווץ לZIP שנחתם .
        '''</summary>
        Friend Shared ReadOnly Property SignVerifyFileZipped() As String
            Get
                Return ResourceManager.GetString("SignVerifyFileZipped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to כלי חתימה ואימות.
        '''</summary>
        Friend Shared ReadOnly Property SignVerifyHeader() As String
            Get
                Return ResourceManager.GetString("SignVerifyHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בחירת קבצים.
        '''</summary>
        Friend Shared ReadOnly Property SignVerifylblSelectFile() As String
            Get
                Return ResourceManager.GetString("SignVerifylblSelectFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הוספת חתימה על הקבצים הנבחרים .
        '''</summary>
        Friend Shared ReadOnly Property SignVerifylblSignExplanation() As String
            Get
                Return ResourceManager.GetString("SignVerifylblSignExplanation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חתימה על קבצים.
        '''</summary>
        Friend Shared ReadOnly Property SignVerifylblSignHeader() As String
            Get
                Return ResourceManager.GetString("SignVerifylblSignHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בדיקת החתימה על  הקבצים הנבחרים       .
        '''</summary>
        Friend Shared ReadOnly Property SignVerifylblVerifyExplanation() As String
            Get
                Return ResourceManager.GetString("SignVerifylblVerifyExplanation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אמת קבצים חתומים.
        '''</summary>
        Friend Shared ReadOnly Property SignVerifylblVerifyHeader() As String
            Get
                Return ResourceManager.GetString("SignVerifylblVerifyHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בחר שם לקובץ החתום.
        '''</summary>
        Friend Shared ReadOnly Property SignVerifySaveDialogTitle() As String
            Get
                Return ResourceManager.GetString("SignVerifySaveDialogTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אודות.
        '''</summary>
        Friend Shared ReadOnly Property SignVerifysplButtonAbout() As String
            Get
                Return ResourceManager.GetString("SignVerifysplButtonAbout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to תוצאות בדיקת אימות.
        '''</summary>
        Friend Shared ReadOnly Property successDiagblbVeriflHeader() As String
            Get
                Return ResourceManager.GetString("successDiagblbVeriflHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אישור.
        '''</summary>
        Friend Shared ReadOnly Property SuccessDiagForm() As String
            Get
                Return ResourceManager.GetString("SuccessDiagForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to שם הקובץ המקורי:.
        '''</summary>
        Friend Shared ReadOnly Property SuccessDiaglblFileLocation() As String
            Get
                Return ResourceManager.GetString("SuccessDiaglblFileLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to שם הקובץ החתום:.
        '''</summary>
        Friend Shared ReadOnly Property SuccessDiaglblFileLocationPdf() As String
            Get
                Return ResourceManager.GetString("SuccessDiaglblFileLocationPdf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הקובץ נחתם בהצלחה !.
        '''</summary>
        Friend Shared ReadOnly Property SuccessDiaglblHeader() As String
            Get
                Return ResourceManager.GetString("SuccessDiaglblHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מיקום הקובץ המקורי:.
        '''</summary>
        Friend Shared ReadOnly Property SuccessDiaglblOriginalFileHeader() As String
            Get
                Return ResourceManager.GetString("SuccessDiaglblOriginalFileHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to סטטוס חתימות.
        '''</summary>
        Friend Shared ReadOnly Property SuccessDiaglblSignatureHistory() As String
            Get
                Return ResourceManager.GetString("SuccessDiaglblSignatureHistory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to החתימה אינה תקינה !.
        '''</summary>
        Friend Shared ReadOnly Property successDiaglblVerificationStatusFailure() As String
            Get
                Return ResourceManager.GetString("successDiaglblVerificationStatusFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to החתימות על הקובץ תקינות.
        '''</summary>
        Friend Shared ReadOnly Property successDiaglblVerificationStatusGreenplural() As String
            Get
                Return ResourceManager.GetString("successDiaglblVerificationStatusGreenplural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to החתימה על הקובץ תקינה.
        '''</summary>
        Friend Shared ReadOnly Property successDiaglblVerificationStatusGreenSignular() As String
            Get
                Return ResourceManager.GetString("successDiaglblVerificationStatusGreenSignular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא בוצעו כל בדיקות האימות בהתאם להגדרות המערכת.
        '''</summary>
        Friend Shared ReadOnly Property successDiaglblVerificationStatusUncheckedPlural() As String
            Get
                Return ResourceManager.GetString("successDiaglblVerificationStatusUncheckedPlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא בוצעו כל בדיקות האימות בהתאם להגדרות המערכת.
        '''</summary>
        Friend Shared ReadOnly Property successDiaglblVerificationStatusUncheckedSingular() As String
            Get
                Return ResourceManager.GetString("successDiaglblVerificationStatusUncheckedSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא ניתן לוודא תקפות של התעודות בזמן החתימה, לפרטים לחץ כאן.
        '''</summary>
        Friend Shared ReadOnly Property successDiaglblVerificationStatusUnknowPlural() As String
            Get
                Return ResourceManager.GetString("successDiaglblVerificationStatusUnknowPlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא ניתן לוודא תקפות התעודה בזמן החתימה, לפרטים לחץ כאן.
        '''</summary>
        Friend Shared ReadOnly Property successDiaglblVerificationStatusUnknowSingular() As String
            Get
                Return ResourceManager.GetString("successDiaglblVerificationStatusUnknowSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לפחות בדיקה אחת נכשלה. לפרטים לחץ כאן.
        '''</summary>
        Friend Shared ReadOnly Property successDiaglblVerificationStatusUnvalidPlural() As String
            Get
                Return ResourceManager.GetString("successDiaglblVerificationStatusUnvalidPlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לפחות בדיקה אחת נכשלה. לפרטים לחץ כאן..
        '''</summary>
        Friend Shared ReadOnly Property successDiaglblVerificationStatusUnvalidSingular() As String
            Get
                Return ResourceManager.GetString("successDiaglblVerificationStatusUnvalidSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא קיימת חתימה על זמן.
        '''</summary>
        Friend Shared ReadOnly Property successDiaglblVerificationTimeStampStatusEmptyPlural() As String
            Get
                Return ResourceManager.GetString("successDiaglblVerificationTimeStampStatusEmptyPlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא קיימת חתימה על זמן.
        '''</summary>
        Friend Shared ReadOnly Property successDiaglblVerificationTimeStampStatusEmptySingular() As String
            Get
                Return ResourceManager.GetString("successDiaglblVerificationTimeStampStatusEmptySingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to החתימה על זמן תקינה.
        '''</summary>
        Friend Shared ReadOnly Property successDiaglblVerificationTimeStampStatusGreenPlural() As String
            Get
                Return ResourceManager.GetString("successDiaglblVerificationTimeStampStatusGreenPlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to החתימה על זמן תקינה.
        '''</summary>
        Friend Shared ReadOnly Property successDiaglblVerificationTimeStampStatusGreenSingular() As String
            Get
                Return ResourceManager.GetString("successDiaglblVerificationTimeStampStatusGreenSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא בוצעו כל בדיקות האימות של החתימה על זמן.
        '''</summary>
        Friend Shared ReadOnly Property successDiaglblVerificationTimeStampStatusUncheckedPlural() As String
            Get
                Return ResourceManager.GetString("successDiaglblVerificationTimeStampStatusUncheckedPlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא בוצעו כל בדיקות האימות של החתימה על זמן.
        '''</summary>
        Friend Shared ReadOnly Property successDiaglblVerificationTimeStampStatusUncheckedSingular() As String
            Get
                Return ResourceManager.GetString("successDiaglblVerificationTimeStampStatusUncheckedSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא ניתן לוודא תקינות חתימה על זמן.
        '''</summary>
        Friend Shared ReadOnly Property successDiaglblVerificationTimeStampStatusUnknowPlural() As String
            Get
                Return ResourceManager.GetString("successDiaglblVerificationTimeStampStatusUnknowPlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא ניתן לוודא תקינות חתימה על זמן.
        '''</summary>
        Friend Shared ReadOnly Property successDiaglblVerificationTimeStampStatusUnknowSingular() As String
            Get
                Return ResourceManager.GetString("successDiaglblVerificationTimeStampStatusUnknowSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לפחות בדיקת חתימה על זמן אחת נכשלה.
        '''</summary>
        Friend Shared ReadOnly Property successDiaglblVerificationTimeStampStatusUnvalidPlural() As String
            Get
                Return ResourceManager.GetString("successDiaglblVerificationTimeStampStatusUnvalidPlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בדיקת חתימה על זמן נכשלה.
        '''</summary>
        Friend Shared ReadOnly Property successDiaglblVerificationTimeStampStatusUnvalidSingular() As String
            Get
                Return ResourceManager.GetString("successDiaglblVerificationTimeStampStatusUnvalidSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מה ברצונך לעשות כעת?.
        '''</summary>
        Friend Shared ReadOnly Property SuccessDiaglblWhat() As String
            Get
                Return ResourceManager.GetString("SuccessDiaglblWhat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to שלח קובץ חתום בדוא&quot;ל.
        '''</summary>
        Friend Shared ReadOnly Property SuccessDiaglnkEmail() As String
            Get
                Return ResourceManager.GetString("SuccessDiaglnkEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פתח תיקייה.
        '''</summary>
        Friend Shared ReadOnly Property SuccessDiaglnkOpenDirectory() As String
            Get
                Return ResourceManager.GetString("SuccessDiaglnkOpenDirectory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פתח קובץ מקורי.
        '''</summary>
        Friend Shared ReadOnly Property SuccessDiaglnkOpenOriginalFile() As String
            Get
                Return ResourceManager.GetString("SuccessDiaglnkOpenOriginalFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פתח קובץ חתום.
        '''</summary>
        Friend Shared ReadOnly Property SuccessDiaglnkOpenOriginalFilePdf() As String
            Get
                Return ResourceManager.GetString("SuccessDiaglnkOpenOriginalFilePdf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to סטטוס חתימות.
        '''</summary>
        Friend Shared ReadOnly Property SuccessDiaglnkViewSignatureHistory() As String
            Get
                Return ResourceManager.GetString("SuccessDiaglnkViewSignatureHistory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to סגור.
        '''</summary>
        Friend Shared ReadOnly Property SuccessDiagOK_Button() As String
            Get
                Return ResourceManager.GetString("SuccessDiagOK_Button", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אימות קובץ חתום.
        '''</summary>
        Friend Shared ReadOnly Property SuccessVerifyDialogForm() As String
            Get
                Return ResourceManager.GetString("SuccessVerifyDialogForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to כן.
        '''</summary>
        Friend Shared ReadOnly Property Yes() As String
            Get
                Return ResourceManager.GetString("Yes", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
