Imports Microsoft.VisualBasic
Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Collections

Namespace SignVerify.Common
    ''' <summary>
    ''' Represents the public interface which should be implemented by each Crypto Provider<br />
    ''' generic interface and is the base interface of all generic Crypto priveder.
    ''' <typeparam name="R">Interface type</typeparam>
    ''' <example>
    ''' <para>
    ''' This example creates a xmlDigSig signed data by using lDigSigProvider.<br />
    ''' The data is signed by using a signer private key, and the signature is verified. <br />
    ''' The example uses the <see cref="CryptoSignedObject">CryptoSignedObject</see>, which allows a data to be signed and countersigned by one or more signers.
    ''' </para>
    ''' 
    ''' <para>
    ''' <list type="bullet">
    ''' <listheader><description>This example uses the following classes:</description></listheader>
    ''' <item><see cref="CryptoSignedObject">CryptoSignedObject</see></item>
    ''' <item><see cref="Certificate">Certificate</see> </item>
    ''' <item><see cref="VerifyParameters">VerifyParameters</see></item>
    ''' <item><see cref="SignParameters">SignParameters</see> </item>
    ''' 
    ''' <item><see cref="CryptoSignedObject">CryptoSignedObject</see></item>
    ''' <item><see cref="System.Security.Cryptography.X509Certificates.X509Store">X509Store</see> </item>
    ''' <item><see cref="System.Security.Cryptography.X509Certificates.X509Certificate2">X509Certificate2</see> </item>
    ''' <item><see cref="System.Security.Cryptography.X509Certificates.X509Certificate2Collection">X509Certificate2Collection </see> </item>
    ''' <item><see cref="System.Security.Cryptography.X509Certificates.X509Store">X509Store</see> </item>
    ''' </list>
    ''' </para>
    ''' To run on a single computer, this example requires the following: <br />
    ''' At leat one certificate with his associated private key stored on the single computer.<br />
    '''<br /><h4> <b><u>Explanation about creating a new certificate:</u></b></h4>
    '''Set up this example by using the Makecert.exe utility, one of several ways to do so. <br />
    ''' <seealso href = "http://msdn2.microsoft.com/en-us/library/bfsktky3(VS.80).aspx">Certificate Creation Tool (Makecert.exe)</seealso> is a convenient utility for testing certificates. <br />
    ''' In a production environment, certificates are generated by a certification authority.<br />
    ''' The following Makecert commands generate the required public key certificates and private keys - Makecert -n "CN=MessageSigner1" -ss My<br />
    ''' These commands place the appropriate public key certificates in the My certificate store.<br />
    ''' These commands place the appropriate public key certificates in the My certificate store.<br />
    ''' To get the public key certificate for subject name "Recipient1" in the AddressBook certificate store,<br />
    ''' export the public key certificate, and then import it into the AddressBook store by following the procedure in How to: <br />
    ''' 
    ''' <seealso href = "http://msdn2.microsoft.com/en-us/library/ms180963(VS.80).aspx">Export and Import a Public Key Certificate</seealso>
    ''' <code lang="vb" title="This example creates a xmlDigSig signed data by using lDigSigProvider:">
    ''' <code source="D:\WorkingFolders\AGAT Projects\SignVerify_2\SignVerify\Samples\UsingProviders\SignVerify.vb" />
    ''' </code>
    ''' 
    ''' </example>
    ''' <example>
    ''' <para>
    ''' The second example verifies an existing signed file by using lDigSigProvider.<br />
    ''' The data is signed by using a signer private key, and the signature is verified. <br />
    ''' The example uses the <see cref="CryptoSignedObject">CryptoSignedObject</see>, which allows a data to be signed and countersigned by one or more signers.
    ''' The file is verified and then the original data is writen to file.
    ''' </para>
    ''' 
    ''' <para>
    ''' <list type="bullet">
    ''' <listheader><description>This example uses the following classes:</description></listheader>
    ''' <item><see cref="CryptoSignedObject">CryptoSignedObject</see></item>
    ''' <item><see cref="Certificate">Certificate</see> </item>
    ''' <item><see cref="VerifyParameters">VerifyParameters</see></item>
    ''' <item><see cref="SignParameters">SignParameters</see> </item>
    ''' 
    ''' <item><see cref="CryptoSignedObject">CryptoSignedObject</see></item>
    ''' <item><see cref="System.Security.Cryptography.X509Certificates.X509Store">X509Store</see> </item>
    ''' <item><see cref="System.Security.Cryptography.X509Certificates.X509Certificate2">X509Certificate2</see> </item>
    ''' <item><see cref="System.Security.Cryptography.X509Certificates.X509Certificate2Collection">X509Certificate2Collection </see> </item>
    ''' <item><see cref="System.Security.Cryptography.X509Certificates.X509Store">X509Store</see> </item>
    ''' </list>
    ''' </para>
    '''     <code lang="C#" title="This example veirfies a xmlDigSig signed data by using lDigSigProvider then extract and write the original content to new file :">
    '''     <code source="D:\WorkingFolders\AGAT Projects\SignVerify_2\SignVerify\Samples\UsingProvideFromFile\Program.vb" />
    '''     </code>
    ''' </example>
    ''' </summary>
    Public Interface ICryptoProvider(Of R) 'where R :
        Inherits IBaseCryptoProvider

        ''' <summary>
        ''' This method signs the specified object using the <see cref="Common.SignParameters">sign parameters</see>.
        ''' </summary>
        ''' <param name="objectToSign">The object to sign (can be in any format).</param>
        ''' <param name="signingParameters">The <see cref="Common.SignParameters">sign parameters</see>.</param>
        ''' <returns>The<see cref="CryptoSignatureInfo">crypto signed object</see> signed according to the sign parameters. </returns>
        Function Sign(ByVal objectToSign As R, ByVal signingParameters As SignParameters) As CryptoSignedObject(Of R)

        ''' <summary>
        ''' This method cosigns the specified object.
        ''' The specified object is already signed object which will be cosigned
        ''' according to <see cref="CoSignParameters">CoSignParameters</see>.
        ''' </summary>
        ''' <param name="objectToSign">The object to sign.</param>
        ''' <param name="signingParameters">The <see cref="CoSignParameters">CoSignParameters</see>.</param>
        ''' <returns>The<see cref="CryptoSignatureInfo">crypto signed object</see> signed according to the sign parameters. </returns>
        ''' <remarks>The cosigned object is cosigned according to cosigning parameters:
        ''' <list>
        ''' <item><see cref="SignVerify.Common.CoSignType">Cosign type</see> (default - parallel)</item>
        ''' <item>The <see cref="Common.SignParameters">sign parameters.</see></item>
        ''' </list> </remarks>
        Function CoSign(ByVal objectToSign As R, ByVal signingParameters As CoSignParameters) As CryptoSignedObject(Of R)

        ''' <summary>
        ''' This method verifies the specified signed object.
        ''' The specified object is a signed object which need to be verified
        ''' according to <see cref="VerifyParameters">VerifyParameters</see>.
        ''' </summary>
        ''' <param name="signedObject">The signed object.</param>
        ''' <param name="verifyParametersInfo">The <see cref="VerifyParameters">verify parameters</see> info.</param>
        ''' <returns>Returns the verified <see cref="CryptoSignedObject">CryptoSignedObject</see>.</returns>
        ''' <remarks>The signed object is verified according to verification parameters:
        ''' <list>
        ''' <item>Trust chain (default - false)</item>
        ''' <item>Trust CRL (default - false)</item>
        ''' </list> </remarks>
        Function VerifySignature(ByVal signedObject As R, ByVal verifyParametersInfo As VerifyParameters) As CryptoSignedObject(Of R)

    End Interface
End Namespace
