'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ErrorMessages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SignVerify.GUI.ErrorMessages", GetType(ErrorMessages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הפעולה הופסקה ע&quot;י המשתמש.
        '''</summary>
        Friend Shared ReadOnly Property CancelAction() As String
            Get
                Return ResourceManager.GetString("CancelAction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא נבחרה תעודה.
        '''</summary>
        Friend Shared ReadOnly Property CertificateHeader() As String
            Get
                Return ResourceManager.GetString("CertificateHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פעולת החתימה  במקביל הופסקה על ידי המשתמש.
        '''</summary>
        Friend Shared ReadOnly Property coSignCanceled() As String
            Get
                Return ResourceManager.GetString("coSignCanceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא ניתן לחתום במקביל על קובץ בעל תקן חתימה שונה!.
        '''</summary>
        Friend Shared ReadOnly Property CosignDifferentProvider() As String
            Get
                Return ResourceManager.GetString("CosignDifferentProvider", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פעולת החתימה במקביל נכשלה.
        '''</summary>
        Friend Shared ReadOnly Property CosignFailed() As String
            Get
                Return ResourceManager.GetString("CosignFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חתימה במקביל נכשלה.
        '''</summary>
        Friend Shared ReadOnly Property CosignHeader() As String
            Get
                Return ResourceManager.GetString("CosignHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חתימה נוספת נכשלה.
        '''</summary>
        Friend Shared ReadOnly Property CoSigningFailed() As String
            Get
                Return ResourceManager.GetString("CoSigningFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to גרסה זו אינה תומכת בהוספת חתימה בתקן PKCS7 בעת חתימה נוספת..
        '''</summary>
        Friend Shared ReadOnly Property CosignPKCS7NotAllowed() As String
            Get
                Return ResourceManager.GetString("CosignPKCS7NotAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to גרסה זו אינה תומכת בהוספת חתימה בתקן Xades בעת חתימה נוספת..
        '''</summary>
        Friend Shared ReadOnly Property CosignXadesNotAllowed() As String
            Get
                Return ResourceManager.GetString("CosignXadesNotAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to תקן חתימה שונה.
        '''</summary>
        Friend Shared ReadOnly Property DifferentProviderHeader() As String
            Get
                Return ResourceManager.GetString("DifferentProviderHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הורדת הקובץ נכשלה.
        '''</summary>
        Friend Shared ReadOnly Property DownloadFailed() As String
            Get
                Return ResourceManager.GetString("DownloadFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to שגיאה כללית.
        '''</summary>
        Friend Shared ReadOnly Property GeneralError() As String
            Get
                Return ResourceManager.GetString("GeneralError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to התעודה אינה מכילה מפתח פרטי ולא ניתן להשתמש בה לחתימה.
        '''</summary>
        Friend Shared ReadOnly Property MissingCertificatePrivateKey() As String
            Get
                Return ResourceManager.GetString("MissingCertificatePrivateKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בחר תעודה לביצוע החתימה.
        '''</summary>
        Friend Shared ReadOnly Property NoCertificate() As String
            Get
                Return ResourceManager.GetString("NoCertificate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הקובץ אינו יכול להיות מאומת, הקובץ אינו קובץ חתום תקין..
        '''</summary>
        Friend Shared ReadOnly Property NotAVerifiedFile() As String
            Get
                Return ResourceManager.GetString("NotAVerifiedFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to תקן חתימה {0} אינו מתאים.
        '''</summary>
        Friend Shared ReadOnly Property ProfileNotFit() As String
            Get
                Return ResourceManager.GetString("ProfileNotFit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הספק אינו מאושר עבור חתימה.
        '''</summary>
        Friend Shared ReadOnly Property ProviderUnvalid() As String
            Get
                Return ResourceManager.GetString("ProviderUnvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to יש חובה לבחור תעודה לצורך ביצוע החתימה.
        '''</summary>
        Friend Shared ReadOnly Property selectCertificate() As String
            Get
                Return ResourceManager.GetString("selectCertificate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to יש חובה לבחור ספק לביצוע החתימה.
        '''</summary>
        Friend Shared ReadOnly Property SelectProvider() As String
            Get
                Return ResourceManager.GetString("SelectProvider", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא ניתן להציג את פרטי התעודה המבוקשת.
        '''</summary>
        Friend Shared ReadOnly Property ShowCert() As String
            Get
                Return ResourceManager.GetString("ShowCert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הצגת תעודה.
        '''</summary>
        Friend Shared ReadOnly Property ShowCertHeader() As String
            Get
                Return ResourceManager.GetString("ShowCertHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פעולת החתימה הופסקה על ידי המשתמש.
        '''</summary>
        Friend Shared ReadOnly Property SignCanceled() As String
            Get
                Return ResourceManager.GetString("SignCanceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פעולת החתימה נכשלה.
        '''</summary>
        Friend Shared ReadOnly Property SignFailed() As String
            Get
                Return ResourceManager.GetString("SignFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חתימה נכשלה.
        '''</summary>
        Friend Shared ReadOnly Property SignHeader() As String
            Get
                Return ResourceManager.GetString("SignHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to שליחת הקובץ החתום נכשלה.
        '''</summary>
        Friend Shared ReadOnly Property UploadFailed() As String
            Get
                Return ResourceManager.GetString("UploadFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to החתימות הקיימות לא יכולות להיות מאומתות.
        '''</summary>
        Friend Shared ReadOnly Property ValidateSignatures() As String
            Get
                Return ResourceManager.GetString("ValidateSignatures", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פעולת האימות הופסקה על ידי המשתמש.
        '''</summary>
        Friend Shared ReadOnly Property VerifyCanceled2() As String
            Get
                Return ResourceManager.GetString("VerifyCanceled2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אימות חתימה נכשל.
        '''</summary>
        Friend Shared ReadOnly Property VerifyHeader() As String
            Get
                Return ResourceManager.GetString("VerifyHeader", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
