'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class InfoMessages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SignVerify.GUI.InfoMessages", GetType(InfoMessages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לתמיכה אנא התקשר ל-1800-200-560.
        '''</summary>
        Friend Shared ReadOnly Property CallForSuport() As String
            Get
                Return ResourceManager.GetString("CallForSuport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to התעודה לא תקינה או לא נבדקה.
        '''</summary>
        Friend Shared ReadOnly Property certificateNotValidOrUnchecked() As String
            Get
                Return ResourceManager.GetString("certificateNotValidOrUnchecked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to סגור את המסך.
        '''</summary>
        Friend Shared ReadOnly Property CloseForm() As String
            Get
                Return ResourceManager.GetString("CloseForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to קובץ בשם XX  כבר קיים במיקום הנבחר. האם לדרוס או ליצור עותק נוסף ?.
        '''</summary>
        Friend Shared ReadOnly Property FileExist() As String
            Get
                Return ResourceManager.GetString("FileExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to שינוי שם הקובץ.
        '''</summary>
        Friend Shared ReadOnly Property FileExistTitleBar() As String
            Get
                Return ResourceManager.GetString("FileExistTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לצורך חתימה, נדרש עדכון תוכנה לשימוש בכרטיס חכם . אנא התקן את הגרסה חדשה מהקישור הבא:.
        '''</summary>
        Friend Shared ReadOnly Property InstallCSP() As String
            Get
                Return ResourceManager.GetString("InstallCSP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to עדכן גרסה.
        '''</summary>
        Friend Shared ReadOnly Property InstallCSPHeader() As String
            Get
                Return ResourceManager.GetString("InstallCSPHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חפש את הקובץ לחתימה \ אימות.
        '''</summary>
        Friend Shared ReadOnly Property OptionBrowseButtonToolTip() As String
            Get
                Return ResourceManager.GetString("OptionBrowseButtonToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בטל את שמירת ההגדרות.
        '''</summary>
        Friend Shared ReadOnly Property OptionNotSaveSetting() As String
            Get
                Return ResourceManager.GetString("OptionNotSaveSetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to שמור את ההגדרות.
        '''</summary>
        Friend Shared ReadOnly Property OptionSaveSetting() As String
            Get
                Return ResourceManager.GetString("OptionSaveSetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הצג פרטי תעודה.
        '''</summary>
        Friend Shared ReadOnly Property OptionShowCerteficate() As String
            Get
                Return ResourceManager.GetString("OptionShowCerteficate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to במסך זה ניתן להגדיר את אופן הצגת החתימה בקבצי PDF חתומים-  גרפיקה.
        '''</summary>
        Friend Shared ReadOnly Property picboxAppearance() As String
            Get
                Return ResourceManager.GetString("picboxAppearance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בחר את התעודה איתה ברצונך לבצע את החתימה.
        '''</summary>
        Friend Shared ReadOnly Property picBoxCertificate() As String
            Get
                Return ResourceManager.GetString("picBoxCertificate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בחר האם אתה רוצה לחתום את הקובץ חתימה מעל או במקביל לחתימה.
        '''</summary>
        Friend Shared ReadOnly Property picBoxCosign() As String
            Get
                Return ResourceManager.GetString("picBoxCosign", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to במסך זה ניתן להגדיר את אופן הצגת החתימה בקבצי PDF חתומים- מאפיינים .
        '''</summary>
        Friend Shared ReadOnly Property picboxDataAppearance() As String
            Get
                Return ResourceManager.GetString("picboxDataAppearance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בחר את הפרופיל בו אתה רוצה להשתמש לביצוע החתימה.
        '''</summary>
        Friend Shared ReadOnly Property picBoxProfile() As String
            Get
                Return ResourceManager.GetString("picBoxProfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בחר את המיקום בו אתה רוצה לשמור את הקובץ.
        '''</summary>
        Friend Shared ReadOnly Property picboxSaveFile() As String
            Get
                Return ResourceManager.GetString("picboxSaveFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בחר את הגדרות החתימה איתן ברצונך לבצע חתימה.
        '''</summary>
        Friend Shared ReadOnly Property picBoxSignSetting() As String
            Get
                Return ResourceManager.GetString("picBoxSignSetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בחר את הגדרות האימות איתן ברצונך לבצע אימות.
        '''</summary>
        Friend Shared ReadOnly Property picBoxVerifySetting() As String
            Get
                Return ResourceManager.GetString("picBoxVerifySetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to מאתר תקן חתימה מתאים:.
        '''</summary>
        Friend Shared ReadOnly Property ProviderCheck() As String
            Get
                Return ResourceManager.GetString("ProviderCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הצג תעודות שהונפקו על ידי גורמים מאושרים.
        '''</summary>
        Friend Shared ReadOnly Property RepudiationMessageCancel() As String
            Get
                Return ResourceManager.GetString("RepudiationMessageCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הצג תעודות שהונפקו על ידי גורם שאינו מאושר.
        '''</summary>
        Friend Shared ReadOnly Property RepudiationMessageOK() As String
            Get
                Return ResourceManager.GetString("RepudiationMessageOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to סמן היכן ברצונך לשמור את הקובץ החתום.
        '''</summary>
        Friend Shared ReadOnly Property SaveFileBrowse() As String
            Get
                Return ResourceManager.GetString("SaveFileBrowse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הצג את פרטי הפרופיל שנבחר לחתימה.
        '''</summary>
        Friend Shared ReadOnly Property ShowProfile() As String
            Get
                Return ResourceManager.GetString("ShowProfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to תוכל בעתיד לבחור להציג מסך זה מתוך הגדרות המערכת.
        '''</summary>
        Friend Shared ReadOnly Property ShowSignOptionDiag() As String
            Get
                Return ResourceManager.GetString("ShowSignOptionDiag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הצג אפשרויות מתקדמות.
        '''</summary>
        Friend Shared ReadOnly Property ShowSignOptionDiagHeader() As String
            Get
                Return ResourceManager.GetString("ShowSignOptionDiagHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to צמצם את סטטוס החתימות.
        '''</summary>
        Friend Shared ReadOnly Property SignatureTreeCollapse() As String
            Get
                Return ResourceManager.GetString("SignatureTreeCollapse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פתח את סטטוס החתימות.
        '''</summary>
        Friend Shared ReadOnly Property SignatureTreeExpand() As String
            Get
                Return ResourceManager.GetString("SignatureTreeExpand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to גורם מאשר לא נבדק.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblChainUncheckd() As String
            Get
                Return ResourceManager.GetString("signatureViewlblChainUncheckd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to גורם מאשר לא תקין.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblChainUnvalid() As String
            Get
                Return ResourceManager.GetString("signatureViewlblChainUnvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to גורם מאשר תקין.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblChainValid() As String
            Get
                Return ResourceManager.GetString("signatureViewlblChainValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא ניתן לבדוק האם התעודה ברשימת התעודות הפסולות.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblCRLNotAbleToCheck() As String
            Get
                Return ResourceManager.GetString("signatureViewlblCRLNotAbleToCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to התעודות הפסולות לא נבדקו.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblCRLUncheckd() As String
            Get
                Return ResourceManager.GetString("signatureViewlblCRLUncheckd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to התעודה ברשימת התעודות הפסולות.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblCRLUnvalid() As String
            Get
                Return ResourceManager.GetString("signatureViewlblCRLUnvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to התעודה אינה ברשימת התעודות הפסולות.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblCRLValid() As String
            Get
                Return ResourceManager.GetString("signatureViewlblCRLValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to תוקף התעודה פג.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblEndCertDate() As String
            Get
                Return ResourceManager.GetString("signatureViewlblEndCertDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to התעודה לא נבדקה.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblEndCerUncheckd() As String
            Get
                Return ResourceManager.GetString("signatureViewlblEndCerUncheckd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to החתימה אינה תקינה.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblEndCerUnvalid() As String
            Get
                Return ResourceManager.GetString("signatureViewlblEndCerUnvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to החתימה תקינה.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblEndCerValid() As String
            Get
                Return ResourceManager.GetString("signatureViewlblEndCerValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to החתימה לא מכסה את כל המסמך..
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblNotCoverWholeDocument() As String
            Get
                Return ResourceManager.GetString("signatureViewlblNotCoverWholeDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to תוקף תעודה עבר.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblTitleCertificateExpired() As String
            Get
                Return ResourceManager.GetString("signatureViewlblTitleCertificateExpired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חתימה חלקית.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblTitleNotCoverWholeDocument() As String
            Get
                Return ResourceManager.GetString("signatureViewlblTitleNotCoverWholeDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא נבדק.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblTitleUnchecked() As String
            Get
                Return ResourceManager.GetString("signatureViewlblTitleUnchecked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא ידוע.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblTitleUnknown() As String
            Get
                Return ResourceManager.GetString("signatureViewlblTitleUnknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא תקין.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblTitleUnvalid() As String
            Get
                Return ResourceManager.GetString("signatureViewlblTitleUnvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to תקין.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblTitleValid() As String
            Get
                Return ResourceManager.GetString("signatureViewlblTitleValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to תקין.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblTSGranted() As String
            Get
                Return ResourceManager.GetString("signatureViewlblTSGranted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא קיים.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblTSNotAdded() As String
            Get
                Return ResourceManager.GetString("signatureViewlblTSNotAdded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא תקין.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblTSRejected() As String
            Get
                Return ResourceManager.GetString("signatureViewlblTSRejected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בקשת זמן החתימה התקבלה.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblTSStateGranted() As String
            Get
                Return ResourceManager.GetString("signatureViewlblTSStateGranted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בקשת זמן החתימה נדחתה.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblTSStateRejection() As String
            Get
                Return ResourceManager.GetString("signatureViewlblTSStateRejection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to זמן החתימה לא התבקש.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewlblTSStateUnChecked() As String
            Get
                Return ResourceManager.GetString("signatureViewlblTSStateUnChecked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to זמן מקומי:.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewLT() As String
            Get
                Return ResourceManager.GetString("signatureViewLT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הזמן האוניברסלי המתואם, השעון הבסיסי בעולם שלפיו נמדדים ומתואמים השעונים במדינות השונות.
        '''</summary>
        Friend Shared ReadOnly Property signatureViewUTC() As String
            Get
                Return ResourceManager.GetString("signatureViewUTC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בטל את פעולת החתימה.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionCancel() As String
            Get
                Return ResourceManager.GetString("SignOptionCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to בחר תעודה לצורך החתימה.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionOpenCert() As String
            Get
                Return ResourceManager.GetString("SignOptionOpenCert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חתום על הקובץ שנבחר.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionSign() As String
            Get
                Return ResourceManager.GetString("SignOptionSign", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אמת את הקובץ שנבחר.
        '''</summary>
        Friend Shared ReadOnly Property SignOptionVerify() As String
            Get
                Return ResourceManager.GetString("SignOptionVerify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פתח את תיקיית הקובץ החתום.
        '''</summary>
        Friend Shared ReadOnly Property successOpenFolder() As String
            Get
                Return ResourceManager.GetString("successOpenFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פתח את הקובץ המקורי.
        '''</summary>
        Friend Shared ReadOnly Property successOpenOriginalFile() As String
            Get
                Return ResourceManager.GetString("successOpenOriginalFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פתח סטטוס חתימות.
        '''</summary>
        Friend Shared ReadOnly Property successOpenSignatureStatus() As String
            Get
                Return ResourceManager.GetString("successOpenSignatureStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to שמור את הקובץ המקורי.
        '''</summary>
        Friend Shared ReadOnly Property successSaveOrigianlFile() As String
            Get
                Return ResourceManager.GetString("successSaveOrigianlFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to שלח קובץ חתום בדוא&quot;ל.
        '''</summary>
        Friend Shared ReadOnly Property successSendFileByEMAIL() As String
            Get
                Return ResourceManager.GetString("successSendFileByEMAIL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לצורך חתימה, נדרש עדכון תוכנה לשימוש בכרטיס חכם . אנא התקן את הגרסה חדשה מהקישור הבא:.
        '''</summary>
        Friend Shared ReadOnly Property UpgradeCSP() As String
            Get
                Return ResourceManager.GetString("UpgradeCSP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to עדכן גרסה.
        '''</summary>
        Friend Shared ReadOnly Property UpgradeCSPHeader() As String
            Get
                Return ResourceManager.GetString("UpgradeCSPHeader", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
