'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ErrorMessges
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SignVerify.Providers.XmlDigSig.ErrorMessges", GetType(ErrorMessges).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to המידע לא מצוי על הקובץ..
        '''</summary>
        Friend Shared ReadOnly Property EmptyData() As String
            Get
                Return ResourceManager.GetString("EmptyData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to חתימה במקביל נכשלה מאחר ולא קיימת תעודה על הקובץ החתום..
        '''</summary>
        Friend Shared ReadOnly Property NoCerteficateFound() As String
            Get
                Return ResourceManager.GetString("NoCerteficateFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to לא ניתן להשתמש בתעודה זו לחתימה מאחר שהיא אינה מכילה מפתח פרטי..
        '''</summary>
        Friend Shared ReadOnly Property NotContainingPrivateKey() As String
            Get
                Return ResourceManager.GetString("NotContainingPrivateKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הקובץ חתום בתקו PKCS7 הוא אינו יכול להיחתם שוב באמצעות תקן שונה..
        '''</summary>
        Friend Shared ReadOnly Property OtherProvider() As String
            Get
                Return ResourceManager.GetString("OtherProvider", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to פעולת החתימה הופסקה על ידי המשתמש.
        '''</summary>
        Friend Shared ReadOnly Property SignCanceled() As String
            Get
                Return ResourceManager.GetString("SignCanceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to החתימה נכשלה, הסתכל בקובץ השגיאות לקבלת פרטים נוספים. .
        '''</summary>
        Friend Shared ReadOnly Property SignFailed() As String
            Get
                Return ResourceManager.GetString("SignFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to אמות נכשל מאחר ולא קיימת תעודה על הקובץ החתום..
        '''</summary>
        Friend Shared ReadOnly Property VeiifyNoCerteficate() As String
            Get
                Return ResourceManager.GetString("VeiifyNoCerteficate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to האימות נכשל, הסתכל בקובץ השגיאות לקבלת פרטים נוספים. .
        '''</summary>
        Friend Shared ReadOnly Property VerifyFailed() As String
            Get
                Return ResourceManager.GetString("VerifyFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to הסיסמא שהוקשה שגויה, נסה שנית..
        '''</summary>
        Friend Shared ReadOnly Property WrongPinCode() As String
            Get
                Return ResourceManager.GetString("WrongPinCode", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
